version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: cron
      cronjob: "0 9 * * *"
      timezone: Asia/Shanghai
    allow:
      - dependency-name: xclienttransaction
    open-pull-requests-limit: 1
